### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by ivan-burazin** [daytonaio/daytona-docker-extension#6]
After i purge existing Daytona installation according to steps: https://www.daytona.io/docs/installation/installation/

I install Daytona via the Docker extension and get stuck on loading screen.
![Screenshot 2024-11-27 at 11 54 37](https://github.com/user-attachments/assets/041a8503-9128-453a-b861-a085299bda56)

MacOS

**Comment by Tpuljak** [comment]
Closed with #8
